module.exports = ['“Te haré saber que la semana pasada me pinché un dedo del pie y sólo lloré durante 20 minutos.” – Bob Esponja',
    '“El hogar es donde estás rodeado de otras criaturas que se preocupan por ti.” – Arenitas Mejillas',
    '"Si crees en ti mismo y con una pequeña pizca de magia, todos tus sueños pueden hacerse realidad.” – Bob Esponja',
    '“A veces tenemos que ir a lo profundo de nosotros mismos para resolver nuestros problemas.” – Patricio Estrella',
    '“Nadie puede cambiar a una persona, pero alguien puede ser una razón para que esa persona cambie”. – Bob Esponja',
    '“La gente tonta siempre es felizmente inconsciente de lo tontos que son en realidad…” – Patricio Estrella',
    '“La gente buena no le arranca los brazos a los demás”. – Bob Esponja',
    '“A veces tenemos que ir a lo profundo de nosotros mismos para resolver nuestros problemas.” – Patricio Estrella',
    '“Sé de un lugar donde nunca te hacen daño. Un lugar mágico con un encanto mágico. En el interior. Interior. Interior. Llévate el centavo”. – Bob Esponja',
    '“No siempre es lo que dices lo que importa, a veces es lo que no dices.” – Don Cangrejo',
    '“Ya eres un hombre, Bob Esponja, y es hora de que empieces a actuar como tal”. – Patricio Estrella',
    '“Soy feo y estoy orgulloso”. – Bob Esponja',
    '“¿Puedes devolverle a Bob Esponja su cerebro? Tuve que pedirlo prestado por una semana.” – Patricio Estrella',
    '“¡Eso es, señor! ¡Acaba de perder sus privilegios cerebrales!” – Plancton',
    '“Disculpe, señor, pero está sentado sobre mi cuerpo, que también es mi cara.” – Bob Esponja',
    '“Lástima que Bob Esponja no esté aquí para disfrutar de que Bob Esponja no esté aquí.” –Calamardo',
    '“Con la imaginación, puedes ser lo que quieras.” – Bob Esponja',
    '“Esta no es la típica oscuridad de todos los días. Esto es… oscuridad avanzada. Hey, si cierro los ojos no parece tan oscuro.” – Bob Esponja ',
    '“Bob Esponja: adivina qué día es hoy”. Patrick: ¿día del calamar molesto? Bob Esponja: ¡no tonto! ¡está en el 15!”. – Bob Esponja y Patricio Estrella',
    '“Bueno, no es un secreto que lo mejor de un secreto es contarle a alguien tu secreto, añadiendo así otro secreto a su colección secreta de secretos, en secreto”. – Bob Esponja',
    '“Las maquinaciones internas de mi mente son un enigma”. – Patricio Estrella',
    '“Moss siempre apunta a la civilización”. – Bob Esponja',
    '“¡Supongo que la hibernación es lo opuesto al sueño de belleza!” – Patricio Estrella',
    '“¡Corre, Don Cangrejo! ¡Corre como si no estuvieras en coma!” – Bob Esponja',
    '“¿Puedo tener la atención de todos?… Tengo que usar el baño.” – Patricio Estrella',
    '“Rápido, Patricio, sin pensar: si pudieras tener algo ahora mismo, ¿qué sería? Patricio: Um… más tiempo para pensar.” – Bob Esponja',
    '“Nunca conseguirás lo que quieres si siempre dejas que la gente te pise.” – Plancton',
    '“Ravioles Ravioles, dame el formuoli.” – Bob Esponja',
    '“¡Bob Esponja es el único tipo que conozco que puede divertirse con una medusa… …durante 12 horas!” – Calamardo',
    '“No te atrevas a tomar el nombre de Texas en vano”. – Arenitas Mejillas',
    '“Siempre sigue a tu corazón a menos que tu corazón sea malo con las instrucciones.” – Bob Esponja',
    '“Ves, ya nadie dice “genial”. Eso es algo tan viejo. Ahora decimos “coral”, como en “Esa operación de nariz es tan coral”. – Perlita',
    '“Bueno, puede ser estúpido, pero también es tonto”. – Patricio Estrella',
    '“Gary, estoy absorbiendo sus golpes como si estuviera hecho de algún tipo de material esponjoso.” – Bob Esponja',
    '“No puedes engañarme. ¡Escucho la radio pública!” – Calamardo',
    '“Si hay algo que disfrutamos los atlantes es una saludable dosis de humor negro”. – Señor Alteza Real',
    '“¡Oh bueno, supongo que hoy no llevo pantalones!” – Bob Esponja',
    '¿”Pastel de carne holográfico”? ¡Mi favorito!” – Plancton',
    '“No necesitas una licencia para conducir un sándwich”. – Bob Esponja',
    '“Nunca le negaremos a un huésped ni la más ridícula petición.”  – Don Cangrejo',
    '“Bob Esponja: ¿Qué es mejor que servir sonrisas?  Estar muerto o cualquier otra cosa.” – Calamardo',
    '“Soy tan leal que no me importa dormir en el suelo frío y duro mientras el Capitán Cangrejo duerme en su cálida y seca tienda”. – Bob Esponja',
    '“Bueno, tal y como yo lo veo, hay tres posibilidades: Una, la robaste; dos, la robaste; o tres, ¡la robaste!” – Don Cangrejo',
    '“Nunca se sabe el verdadero valor de un momento, hasta que se convierte en un recuerdo.” – Bob Esponja',
    '“Una palabra de cinco letras para la felicidad… dinero.” – Don Cangrejo',
    '“Si yo muriera ahora mismo en una explosión de fuego por el descuido de un amigo… …entonces estaría bien.” – Bob Esponja',
    '“El conocimiento no puede reemplazar la amistad”. – Patricio Estrella',
    '“Tengo una cabeza cuadrada y un fantasma real tiene una redonda. ¡Todo lo que necesito es hacerla redonda y Boo! Tengo miedo.” – Bob Esponja',
    '“¡Tonterías, mi vocabulario se expande infinitamente!” – Patricio Estrella',
    '“Estoy listo, estoy listo.”',
    '“Mira a todos los jóvenes de moda comiendo ensaladas.”',
    '“El mejor momento para llevar un suéter a rayas es todo el tiempo.”',
    '“¿Puedo ser excusado por el resto de mi vida?”',
    '“Soy fea y estoy orgullosa.” – Bob Esponja',
    '“¡La F es para los amigos que hacen cosas juntos!”',
    '“Todo lo que sé es comer y respirar bien.”',
    '“Ravioles, ravioles. Dame el formuoli.”',
    '“Disculpe, señor, pero está sentado sobre mi cuerpo, que también es mi cara.” – Bob Esponja',
    '“Con la imaginación, puedes ser lo que quieras.”',
    '"Frases finales de Bob Esponja',
    '“Te haré saber que la semana pasada me pinché un dedo del pie y sólo lloré durante 20 minutos.” – Bob Esponja',
    '“Si crees en ti mismo y con una pequeña pizca de magia, todos tus sueños pueden hacerse realidad.” – Bob Esponja',
    '“La gente buena no le arranca los brazos a los demás”. – Bob Esponja']